export const SET_NAVBARINDEX = 'SET_NAVBARINDEX';
export const SET_DRAWERTOPNAVBAR = 'SET_DRAWERTOPNAVBAR';
export const SET_USERLOADING = 'SET_USERLOADING';

// User
export const SET_USER = 'SET_USER';
export const SET_USER_SIGNOUT = 'SET_USER_SIGNOUT';

// ReportDate
export const SET_STARTDATE = 'SET_STARTDATE';
export const SET_ENDDATE = 'SET_ENDDATE';

// Client
export const SET_CLIENT = 'SET_CLIENT';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';

// Product
export const SET_PRODUCT = 'SET_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const SET_CATALOG = 'SET_CATALOG';
export const CREATE_CATALOG = 'CREATE_CATALOG';
export const DELETE_CATALOG = 'DELETE_CATALOG';

// Promotion
export const SET_PROMOTIONS = 'SET_PROMOTIONS';
export const CREATE_PROMOTION = 'CREATE_PROMOTION';
export const DELETE_PROMOTION = 'DELETE_PROMOTION';
export const UPDATE_PROMOTION = 'UPDATE_PROMOTION';

// Employee
export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';

// Order
export const SET_ORDER = 'SET_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';

// Store
export const SET_BRANCH = 'SET_BRANCH';
export const CREATE_BRANCH = 'CREATE_BRANCH';
export const DELETE_BRANCH = 'DELETE_BRANCH';
export const SET_TABLES = 'SET_TABLES';
export const CREATE_TABLE = 'CREATE_TABLE';
export const DELETE_TABLE = 'DELETE_TABLE';
export const UPDATE_TABLE = 'UPDATE_TABLE';
export const UPDATE_BRANCH = 'UPDATE_BRANCH';

// Stock
export const SET_STOCKCATALOG = 'SET_STOCKCATALOG';
export const CREATE_STOCKCATALOG = 'CREATE_STOCKCATALOG';
export const DELETE_STOCKCATALOG = 'DELETE_STOCKCATALOG';
