export const SET_NAVBARINDEX = 'SET_NAVBARINDEX';
export const SET_DRAWERTOPNAVBAR = 'SET_DRAWERTOPNAVBAR';
export const SET_USERLOADING = 'SET_USERLOADING';

// User
export const SET_USER = 'SET_USER';
export const SET_USER_SIGNOUT = 'SET_USER_SIGNOUT';

// ReportDate
export const SET_STARTDATE = 'SET_STARTDATE';
export const SET_ENDDATE = 'SET_ENDDATE';

// Client
export const SET_CLIENT = 'SET_CLIENT';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';

// Store Product
export const SET_STOREPRODUCT = 'SET_STOREPRODUCT';
export const CREATE_STOREPRODUCT = 'CREATE_STOREPRODUCT';
export const DELETE_STOREPRODUCT = 'DELETE_STOREPRODUCT';
export const UPDATE_STOREPRODUCT = 'UPDATE_STOREPRODUCT';
export const SET_STOREPRODUCTCATALOG = 'SET_STOREPRODUCTCATALOG';
export const CREATE_STOREPRODUCTCATALOG = 'CREATE_STOREPRODUCTCATALOG';
export const DELETE_STOREPRODUCTCATALOG = 'DELETE_STOREPRODUCTCATALOG';

// Online Product
export const SET_ONLINEPRODUCT = 'SET_ONLINEPRODUCT';
export const CREATE_ONLINEPRODUCT = 'CREATE_ONLINEPRODUCT';
export const DELETE_ONLINEPRODUCT = 'DELETE_ONLINEPRODUCT';
export const UPDATE_ONLINEPRODUCT = 'UPDATE_ONLINEPRODUCT';
export const SET_ONLINEPRODUCTCATALOG = 'SET_ONLINEPRODUCTCATALOG';
export const CREATE_ONLINEPRODUCTCATALOG = 'CREATE_ONLINEPRODUCTCATALOG';
export const DELETE_ONLINEPRODUCTCATALOG = 'DELETE_ONLINEPRODUCTCATALOG';

// Promotion
export const SET_PROMOTIONS = 'SET_PROMOTIONS';
export const CREATE_PROMOTION = 'CREATE_PROMOTION';
export const DELETE_PROMOTION = 'DELETE_PROMOTION';
export const UPDATE_PROMOTION = 'UPDATE_PROMOTION';

// Employee
export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

// Order
export const SET_ORDER = 'SET_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';

// Store
export const SET_BRANCH = 'SET_BRANCH';
export const CREATE_BRANCH = 'CREATE_BRANCH';
export const DELETE_BRANCH = 'DELETE_BRANCH';
export const SET_TABLES = 'SET_TABLES';
export const CREATE_TABLE = 'CREATE_TABLE';
export const DELETE_TABLE = 'DELETE_TABLE';
export const UPDATE_TABLE = 'UPDATE_TABLE';
export const UPDATE_BRANCH = 'UPDATE_BRANCH';
export const UPDATE_TABLE_ORDER = 'UPDATE_TABLE_ORDER';
export const CLEAR_TABLE = 'CLEAR_TABLE';

// Stock
export const SET_STOCKCATALOG = 'SET_STOCKCATALOG';
export const CREATE_STOCKCATALOG = 'CREATE_STOCKCATALOG';
export const DELETE_STOCKCATALOG = 'DELETE_STOCKCATALOG';
